# ViperSec 2025 Configuration File

version: "2025.1.0"
debug: false
log_level: "INFO"

# Proxy configuration
proxy:
  enabled: false
  http_proxy: null
  https_proxy: null
  rotation_enabled: false
  proxy_list: []

# AI/ML configuration
ai:
  enabled: true
  model_path: "models/"
  response_classifier_model: "bert-base-uncased"
  captcha_solver_enabled: true
  reinforcement_learning: true
  anomaly_detection: true

# Scanning configuration
scan:
  max_threads: 50
  timeout: 30
  max_retries: 3
  delay_between_requests: 0.1
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# Module configuration
modules:
  enabled_modules:
    - "auth"
    - "xss"
    - "sqli"
    - "csrf"
    - "session"
    - "pain_testing"
  
  auth_config:
    test_common_credentials: true
    test_session_fixation: true
    test_user_enumeration: true
  
  xss_config:
    test_reflected: true
    test_stored: true
    test_dom: true
    test_headers: true
  
  sqli_config:
    test_error_based: true
    test_time_based: true
    test_union_based: true
    test_boolean_based: true

# Reporting configuration
reports:
  output_formats:
    - "json"
    - "html"
  template_dir: "templates/"
  include_screenshots: true
  include_payloads: true